INSERT ALL
  INTO ADMINISTRADOR VALUES (2435,'lluna@uach.mx', '$2a$10$5fWtOfJDB1Pr.vXBqgPwbuo1.Ug3I8C59FJhjA.Jo5Q8oxafRZgBa',
                             'Luis Angel','Luna','Hernandez','admin','/uploads/1716277800332-.jpeg')
  INTO ADMINISTRADOR VALUES (113344,'rgonzalez@uach.mx', '$2a$10$Ffaoz1T2oFmIIXrZS8E19uOnN9cLbvOKOze5Uo8HOhpQZZks1Q2kK',
                             'Rogelio','Gonzales','Hernandez','admin',NULL)
  INTO ADMINISTRADOR VALUES (232111,'imacias@uach.mx', '$2a$10$kWbH4yoGSFopnjV5pnaZ3.GZAu.uFPpS30FEnqR4CARvERJ3O7rI.',
                             'Isabel Lourdes','Macias','Garcia','admin',NULL)
SELECT 1 FROM dual;

commit;

/* ===============================================================
   UACH_AS  –  carga inicial de catálogos y datos
   =============================================================== */
SET DEFINE OFF;

/*-----------------------------------------------------------------
  1. CARRERA
-----------------------------------------------------------------*/
INSERT ALL
  INTO CARRERA (ID_CARRERA,NOMBRE_CARRERA) VALUES (0,'Opciones ')
  INTO CARRERA (ID_CARRERA,NOMBRE_CARRERA) VALUES (1,'Ingenieria Aeroespacial')
  INTO CARRERA (ID_CARRERA,NOMBRE_CARRERA) VALUES (2,'Ingenieria Civil')
  INTO CARRERA (ID_CARRERA,NOMBRE_CARRERA) VALUES (3,'Ingenieria en ciencias de la computacion')
  INTO CARRERA (ID_CARRERA,NOMBRE_CARRERA) VALUES (5,'Ingenieria en sistemas computacionales en hardware')
  INTO CARRERA (ID_CARRERA,NOMBRE_CARRERA) VALUES (6,'Ingenieria en sistemas topograficos')
  INTO CARRERA (ID_CARRERA,NOMBRE_CARRERA) VALUES (7,'Ingenieria en tecnologias de procesos ')
  INTO CARRERA (ID_CARRERA,NOMBRE_CARRERA) VALUES (8,'Ingeniero Fisico')
  INTO CARRERA (ID_CARRERA,NOMBRE_CARRERA) VALUES (9,'Ingeniero Geologo')
  INTO CARRERA (ID_CARRERA,NOMBRE_CARRERA) VALUES (871234,'Ingenieria en Alimentos')
SELECT 1 FROM dual;
/

/*-----------------------------------------------------------------
  2. SEMESTRE
-----------------------------------------------------------------*/
INSERT ALL
  INTO SEMESTRE (ID,SEM) VALUES (1,'Primer semestre')
  INTO SEMESTRE (ID,SEM) VALUES (2,'Segundo semestre')
  INTO SEMESTRE (ID,SEM) VALUES (3,'Tercer semestre')
  INTO SEMESTRE (ID,SEM) VALUES (4,'Cuarto semestre')
  INTO SEMESTRE (ID,SEM) VALUES (5,'Quinto semestre')
  INTO SEMESTRE (ID,SEM) VALUES (6,'Sexto semestre')
  INTO SEMESTRE (ID,SEM) VALUES (7,'Septimo semestre')
  INTO SEMESTRE (ID,SEM) VALUES (8,'Octavo semestre')
  INTO SEMESTRE (ID,SEM) VALUES (9,'Noveno semestre')
SELECT 1 FROM dual;
/

/*-----------------------------------------------------------------
  3. HORARIOS  (50 filas = 5 días × 10 horas)
-----------------------------------------------------------------*/
INSERT ALL
  INTO HORARIOS VALUES (1 ,TO_TIMESTAMP('08:00:00','HH24:MI:SS'),'lunes')
  INTO HORARIOS VALUES (2 ,TO_TIMESTAMP('09:00:00','HH24:MI:SS'),'lunes')
  INTO HORARIOS VALUES (3 ,TO_TIMESTAMP('10:00:00','HH24:MI:SS'),'lunes')
  INTO HORARIOS VALUES (4 ,TO_TIMESTAMP('11:00:00','HH24:MI:SS'),'lunes')
  INTO HORARIOS VALUES (5 ,TO_TIMESTAMP('12:00:00','HH24:MI:SS'),'lunes')
  INTO HORARIOS VALUES (6 ,TO_TIMESTAMP('13:00:00','HH24:MI:SS'),'lunes')
  INTO HORARIOS VALUES (7 ,TO_TIMESTAMP('14:00:00','HH24:MI:SS'),'lunes')
  INTO HORARIOS VALUES (8 ,TO_TIMESTAMP('15:00:00','HH24:MI:SS'),'lunes')
  INTO HORARIOS VALUES (9 ,TO_TIMESTAMP('16:00:00','HH24:MI:SS'),'lunes')
  INTO HORARIOS VALUES (10,TO_TIMESTAMP('17:00:00','HH24:MI:SS'),'lunes')
  INTO HORARIOS VALUES (11,TO_TIMESTAMP('08:00:00','HH24:MI:SS'),'martes')
  INTO HORARIOS VALUES (12,TO_TIMESTAMP('09:00:00','HH24:MI:SS'),'martes')
  INTO HORARIOS VALUES (13,TO_TIMESTAMP('10:00:00','HH24:MI:SS'),'martes')
  INTO HORARIOS VALUES (14,TO_TIMESTAMP('11:00:00','HH24:MI:SS'),'martes')
  INTO HORARIOS VALUES (15,TO_TIMESTAMP('12:00:00','HH24:MI:SS'),'martes')
  INTO HORARIOS VALUES (16,TO_TIMESTAMP('13:00:00','HH24:MI:SS'),'martes')
  INTO HORARIOS VALUES (17,TO_TIMESTAMP('14:00:00','HH24:MI:SS'),'martes')
  INTO HORARIOS VALUES (18,TO_TIMESTAMP('15:00:00','HH24:MI:SS'),'martes')
  INTO HORARIOS VALUES (19,TO_TIMESTAMP('16:00:00','HH24:MI:SS'),'martes')
  INTO HORARIOS VALUES (20,TO_TIMESTAMP('17:00:00','HH24:MI:SS'),'martes')
  INTO HORARIOS VALUES (21,TO_TIMESTAMP('08:00:00','HH24:MI:SS'),'miércoles')
  INTO HORARIOS VALUES (22,TO_TIMESTAMP('09:00:00','HH24:MI:SS'),'miércoles')
  INTO HORARIOS VALUES (23,TO_TIMESTAMP('10:00:00','HH24:MI:SS'),'miércoles')
  INTO HORARIOS VALUES (24,TO_TIMESTAMP('11:00:00','HH24:MI:SS'),'miércoles')
  INTO HORARIOS VALUES (25,TO_TIMESTAMP('12:00:00','HH24:MI:SS'),'miércoles')
  INTO HORARIOS VALUES (26,TO_TIMESTAMP('13:00:00','HH24:MI:SS'),'miércoles')
  INTO HORARIOS VALUES (27,TO_TIMESTAMP('14:00:00','HH24:MI:SS'),'miércoles')
  INTO HORARIOS VALUES (28,TO_TIMESTAMP('15:00:00','HH24:MI:SS'),'miércoles')
  INTO HORARIOS VALUES (29,TO_TIMESTAMP('16:00:00','HH24:MI:SS'),'miércoles')
  INTO HORARIOS VALUES (30,TO_TIMESTAMP('17:00:00','HH24:MI:SS'),'miércoles')
  INTO HORARIOS VALUES (31,TO_TIMESTAMP('08:00:00','HH24:MI:SS'),'jueves')
  INTO HORARIOS VALUES (32,TO_TIMESTAMP('09:00:00','HH24:MI:SS'),'jueves')
  INTO HORARIOS VALUES (33,TO_TIMESTAMP('10:00:00','HH24:MI:SS'),'jueves')
  INTO HORARIOS VALUES (34,TO_TIMESTAMP('11:00:00','HH24:MI:SS'),'jueves')
  INTO HORARIOS VALUES (35,TO_TIMESTAMP('12:00:00','HH24:MI:SS'),'jueves')
  INTO HORARIOS VALUES (36,TO_TIMESTAMP('13:00:00','HH24:MI:SS'),'jueves')
  INTO HORARIOS VALUES (37,TO_TIMESTAMP('14:00:00','HH24:MI:SS'),'jueves')
  INTO HORARIOS VALUES (38,TO_TIMESTAMP('15:00:00','HH24:MI:SS'),'jueves')
  INTO HORARIOS VALUES (39,TO_TIMESTAMP('16:00:00','HH24:MI:SS'),'jueves')
  INTO HORARIOS VALUES (40,TO_TIMESTAMP('17:00:00','HH24:MI:SS'),'jueves')
  INTO HORARIOS VALUES (41,TO_TIMESTAMP('08:00:00','HH24:MI:SS'),'viernes')
  INTO HORARIOS VALUES (42,TO_TIMESTAMP('09:00:00','HH24:MI:SS'),'viernes')
  INTO HORARIOS VALUES (43,TO_TIMESTAMP('10:00:00','HH24:MI:SS'),'viernes')
  INTO HORARIOS VALUES (44,TO_TIMESTAMP('11:00:00','HH24:MI:SS'),'viernes')
  INTO HORARIOS VALUES (45,TO_TIMESTAMP('12:00:00','HH24:MI:SS'),'viernes')
  INTO HORARIOS VALUES (46,TO_TIMESTAMP('13:00:00','HH24:MI:SS'),'viernes')
  INTO HORARIOS VALUES (47,TO_TIMESTAMP('14:00:00','HH24:MI:SS'),'viernes')
  INTO HORARIOS VALUES (48,TO_TIMESTAMP('15:00:00','HH24:MI:SS'),'viernes')
  INTO HORARIOS VALUES (49,TO_TIMESTAMP('16:00:00','HH24:MI:SS'),'viernes')
  INTO HORARIOS VALUES (50,TO_TIMESTAMP('17:00:00','HH24:MI:SS'),'viernes')
SELECT 1 FROM dual;
/

/*-----------------------------------------------------------------
  4. MATERIAS   (98 filas)
-----------------------------------------------------------------*/
INSERT ALL
  INTO MATERIAS (ID_MATERIA,N_MAT,N_CARR,N_SEM) VALUES (0 ,'Opciones',0,1)
  INTO MATERIAS (ID_MATERIA,N_MAT,N_CARR,N_SEM) VALUES (1 ,'Algebra superior',1,1)
  INTO MATERIAS (ID_MATERIA,N_MAT,N_CARR,N_SEM) VALUES (2 ,'Calculo diferencial e integral',1,1)
  INTO MATERIAS (ID_MATERIA,N_MAT,N_CARR,N_SEM) VALUES (3 ,'Fisica Basica',1,1)
  INTO MATERIAS (ID_MATERIA,N_MAT,N_CARR,N_SEM) VALUES (4 ,'Dibujo',1,1)
  INTO MATERIAS (ID_MATERIA,N_MAT,N_CARR,N_SEM) VALUES (6 ,'Tecnologia y manejo de la informacion',1,1)
  INTO MATERIAS (ID_MATERIA,N_MAT,N_CARR,N_SEM) VALUES (7 ,'Sociedad y cultura',1,1)
  INTO MATERIAS (ID_MATERIA,N_MAT,N_CARR,N_SEM) VALUES (8 ,'Calculo Aplicado',1,2)
  INTO MATERIAS (ID_MATERIA,N_MAT,N_CARR,N_SEM) VALUES (9 ,'Algebra lineal',1,2)
  INTO MATERIAS (ID_MATERIA,N_MAT,N_CARR,N_SEM) VALUES (10,'Quimica general',1,2)
  INTO MATERIAS (ID_MATERIA,N_MAT,N_CARR,N_SEM) VALUES (11,'Introduccion al desarrollo economico',1,2)
  INTO MATERIAS (ID_MATERIA,N_MAT,N_CARR,N_SEM) VALUES (12,'Ingles 4',1,2)
  INTO MATERIAS (ID_MATERIA,N_MAT,N_CARR,N_SEM) VALUES (14,'Universidad y conocimiento',1,2)
  INTO MATERIAS (ID_MATERIA,N_MAT,N_CARR,N_SEM) VALUES (15,'Ecuaciones diferenciales',1,3)
  INTO MATERIAS (ID_MATERIA,N_MAT,N_CARR,N_SEM) VALUES (16,'Electricidad y magnetismo',1,3)
  INTO MATERIAS (ID_MATERIA,N_MAT,N_CARR,N_SEM) VALUES (17,'Estatica',1,3)
  INTO MATERIAS (ID_MATERIA,N_MAT,N_CARR,N_SEM) VALUES (18,'Programacion',1,3)
  INTO MATERIAS (ID_MATERIA,N_MAT,N_CARR,N_SEM) VALUES (19,'Ingles avanzado',1,3)
  INTO MATERIAS (ID_MATERIA,N_MAT,N_CARR,N_SEM) VALUES (20,'Administracion',1,3)
  INTO MATERIAS (ID_MATERIA,N_MAT,N_CARR,N_SEM) VALUES (21,'Contabilidad',1,3)
  INTO MATERIAS (ID_MATERIA,N_MAT,N_CARR,N_SEM) VALUES (22,'Calculo Vectorial',1,4)
  INTO MATERIAS (ID_MATERIA,N_MAT,N_CARR,N_SEM) VALUES (23,'Dinamica',1,4)
  INTO MATERIAS (ID_MATERIA,N_MAT,N_CARR,N_SEM) VALUES (24,'Metodos Numericos',1,4)
  INTO MATERIAS (ID_MATERIA,N_MAT,N_CARR,N_SEM) VALUES (25,'Mecanica de materiales 1',1,4)
  INTO MATERIAS (ID_MATERIA,N_MAT,N_CARR,N_SEM) VALUES (26,'Probabilidad y estadistica 1',1,4)
  INTO MATERIAS (ID_MATERIA,N_MAT,N_CARR,N_SEM) VALUES (27,'Analisis de circuitos electricos',1,4)
  INTO MATERIAS (ID_MATERIA,N_MAT,N_CARR,N_SEM) VALUES (28,'Ingles Avanzado 2',1,4)
  INTO MATERIAS (ID_MATERIA,N_MAT,N_CARR,N_SEM) VALUES (29,'Probabilidad y estadistica 2',1,5)
  INTO MATERIAS (ID_MATERIA,N_MAT,N_CARR,N_SEM) VALUES (30,'Dibujo Avanzado 1',1,5)
  INTO MATERIAS (ID_MATERIA,N_MAT,N_CARR,N_SEM) VALUES (31,'Ciencia Ambiental',1,5)
  INTO MATERIAS (ID_MATERIA,N_MAT,N_CARR,N_SEM) VALUES (32,'Metalurgia',1,5)
  INTO MATERIAS (ID_MATERIA,N_MAT,N_CARR,N_SEM) VALUES (33,'Mecanica de materiales 2',1,5)
  INTO MATERIAS (ID_MATERIA,N_MAT,N_CARR,N_SEM) VALUES (34,'Termodinamica',1,6)
  INTO MATERIAS (ID_MATERIA,N_MAT,N_CARR,N_SEM) VALUES (35,'Administracion de proyectos',1,6)
  INTO MATERIAS (ID_MATERIA,N_MAT,N_CARR,N_SEM) VALUES (36,'Sistemas de calidad',1,6)
  INTO MATERIAS (ID_MATERIA,N_MAT,N_CARR,N_SEM) VALUES (37,'Aerodinamica 1',1,7)
  INTO MATERIAS (ID_MATERIA,N_MAT,N_CARR,N_SEM) VALUES (38,'Mecanica orbital y espacio ambiental',1,7)
  INTO MATERIAS (ID_MATERIA,N_MAT,N_CARR,N_SEM) VALUES (39,'Estructuras aeroespaciales',1,7)
  INTO MATERIAS (ID_MATERIA,N_MAT,N_CARR,N_SEM) VALUES (40,'Redaccion y comprension',1,7)
  INTO MATERIAS (ID_MATERIA,N_MAT,N_CARR,N_SEM) VALUES (41,'Dinamica y control de vuelo',1,8)
  INTO MATERIAS (ID_MATERIA,N_MAT,N_CARR,N_SEM) VALUES (42,'Propulsion',1,8)
  INTO MATERIAS (ID_MATERIA,N_MAT,N_CARR,N_SEM) VALUES (43,'Ingenieria en sistemas aeroespaciales',1,8)
  INTO MATERIAS (ID_MATERIA,N_MAT,N_CARR,N_SEM) VALUES (44,'Aerodinamica 2',1,8)
  INTO MATERIAS (ID_MATERIA,N_MAT,N_CARR,N_SEM) VALUES (45,'Comunicacion oral',1,8)
  INTO MATERIAS (ID_MATERIA,N_MAT,N_CARR,N_SEM) VALUES (46,'Transferencia de calor',1,9)
  INTO MATERIAS (ID_MATERIA,N_MAT,N_CARR,N_SEM) VALUES (47,'Diseño de cubiertas aeroespaciles',1,9)
  INTO MATERIAS (ID_MATERIA,N_MAT,N_CARR,N_SEM) VALUES (48,'Produccion y manufactura aeroespacial',1,9)
  INTO MATERIAS (ID_MATERIA,N_MAT,N_CARR,N_SEM) VALUES (49,'Calculo Aplicado',2,2)
  INTO MATERIAS (ID_MATERIA,N_MAT,N_CARR,N_SEM) VALUES (51,'Algebra lineal',2,2)
  INTO MATERIAS (ID_MATERIA,N_MAT,N_CARR,N_SEM) VALUES (52,'Ingles 2',2,2)
  INTO MATERIAS (ID_MATERIA,N_MAT,N_CARR,N_SEM) VALUES (53,'Topografia 2',2,2)
  INTO MATERIAS (ID_MATERIA,N_MAT,N_CARR,N_SEM) VALUES (54,'CAD 2',2,2)
  INTO MATERIAS (ID_MATERIA,N_MAT,N_CARR,N_SEM) VALUES (55,'Lenguaje y comunicacion',2,2)
  INTO MATERIAS (ID_MATERIA,N_MAT,N_CARR,N_SEM) VALUES (56,'Universidad y conocimiento',2,2)
  INTO MATERIAS (ID_MATERIA,N_MAT,N_CARR,N_SEM) VALUES (57,'Calculo Vectorial',3,3)
  INTO MATERIAS (ID_MATERIA,N_MAT,N_CARR,N_SEM) VALUES (58,'Algebra Lineal',3,3)
  INTO MATERIAS (ID_MATERIA,N_MAT,N_CARR,N_SEM) VALUES (60,'Ecuaciones diferenciales',3,3)
  INTO MATERIAS (ID_MATERIA,N_MAT,N_CARR,N_SEM) VALUES (61,'Analisis de algoritmos',3,3)
  INTO MATERIAS (ID_MATERIA,N_MAT,N_CARR,N_SEM) VALUES (62,'Ingles 3',3,3)
  INTO MATERIAS (ID_MATERIA,N_MAT,N_CARR,N_SEM) VALUES (72,'Lenguajes de Programacion 3',5,5)
  INTO MATERIAS (ID_MATERIA,N_MAT,N_CARR,N_SEM) VALUES (73,'Analisis de circuitos electricos 2',5,5)
  INTO MATERIAS (ID_MATERIA,N_MAT,N_CARR,N_SEM) VALUES (74,'Ingenieria de software 1',5,5)
  INTO MATERIAS (ID_MATERIA,N_MAT,N_CARR,N_SEM) VALUES (75,'Sistemas operativos 1',5,5)
  INTO MATERIAS (ID_MATERIA,N_MAT,N_CARR,N_SEM) VALUES (76,'Estructura de datos 2',5,5)
  INTO MATERIAS (ID_MATERIA,N_MAT,N_CARR,N_SEM) VALUES (77,'Probabilidad y estadistica 2',5,5)
  INTO MATERIAS (ID_MATERIA,N_MAT,N_CARR,N_SEM) VALUES (78,'Diseño de bases de datos 1',5,5)
  INTO MATERIAS (ID_MATERIA,N_MAT,N_CARR,N_SEM) VALUES (79,'Ajustes',6,6)
  INTO MATERIAS (ID_MATERIA,N_MAT,N_CARR,N_SEM) VALUES (80,'Geodesia Aplicada',6,6)
  INTO MATERIAS (ID_MATERIA,N_MAT,N_CARR,N_SEM) VALUES (81,'Foto Interpretacion',6,6)
  INTO MATERIAS (ID_MATERIA,N_MAT,N_CARR,N_SEM) VALUES (82,'Sistemas de informacion geografica 2',6,6)
  INTO MATERIAS (ID_MATERIA,N_MAT,N_CARR,N_SEM) VALUES (83,'Hidrologia Superficial',6,6)
  INTO MATERIAS (ID_MATERIA,N_MAT,N_CARR,N_SEM) VALUES (84,'Administracion',6,6)
  INTO MATERIAS (ID_MATERIA,N_MAT,N_CARR,N_SEM) VALUES (85,'Contabilidad para ingenieros',6,6)
  INTO MATERIAS (ID_MATERIA,N_MAT,N_CARR,N_SEM) VALUES (86,'Investigacion de operaciones',7,7)
  INTO MATERIAS (ID_MATERIA,N_MAT,N_CARR,N_SEM) VALUES (87,'Fundamentos de la cadena de suministros',7,7)
  INTO MATERIAS (ID_MATERIA,N_MAT,N_CARR,N_SEM) VALUES (88,'Administracion de proyectos 3',7,7)
  INTO MATERIAS (ID_MATERIA,N_MAT,N_CARR,N_SEM) VALUES (89,'Gestoria empresarial 2',7,7)
  INTO MATERIAS (ID_MATERIA,N_MAT,N_CARR,N_SEM) VALUES (90,'Direccion y liderazgo',7,7)
  INTO MATERIAS (ID_MATERIA,N_MAT,N_CARR,N_SEM) VALUES (91,'Analisis instrumental',8,8)
  INTO MATERIAS (ID_MATERIA,N_MAT,N_CARR,N_SEM) VALUES (92,'Recursos Humanos',8,8)
  INTO MATERIAS (ID_MATERIA,N_MAT,N_CARR,N_SEM) VALUES (93,'Evaluacion de yacimientos minerales',9,9)
  INTO MATERIAS (ID_MATERIA,N_MAT,N_CARR,N_SEM) VALUES (94,'Geologia Ambiental',9,9)
  INTO MATERIAS (ID_MATERIA,N_MAT,N_CARR,N_SEM) VALUES (95,'Metodos Electricos',9,9)
  INTO MATERIAS (ID_MATERIA,N_MAT,N_CARR,N_SEM) VALUES (96,'Mecanica de suelos',9,9)
  INTO MATERIAS (ID_MATERIA,N_MAT,N_CARR,N_SEM) VALUES (97,'Quimica del petroleo',9,9)
  INTO MATERIAS (ID_MATERIA,N_MAT,N_CARR,N_SEM) VALUES (98,'Calculo Superior',8,1)
SELECT 1 FROM dual;
/

/*-----------------------------------------------------------------
  5. DOCENTES   (8 filas, sin administradores)
-----------------------------------------------------------------*/
INSERT ALL
  INTO DOCENTES (ID_DOCENTE,NOMBRE_DOC,APELLIDO,CORREO,APEI2,PERFIL,ROL_DOC,CONTRA_DOCENTE,ID_CARRERA_MAT,ID_MAT_AS) VALUES
    (0,'Opciones','', 'opciones@uach.mx','',NULL,'teacher','$2a$10$v4T0Fn4Sk9w3eziDMWlEhOXUT5nBBLllrZ24m6iGzpZBe1W.Z1DZq',0,0)
  INTO DOCENTES VALUES
    (2419,'Luis Gerardo','Chacon','lchacon@uach.mx','Hernandez','/uploads/1716782560679-.png','teacher','$2a$10$rox/.h17N7yHYqxvH6F/Iec7R8ChugtvE/e2Ak5uM9sitG4SbyKNW',3,0)
  INTO DOCENTES VALUES
    (4587,'Juan','Marquez','',          'Rodriguez','n','teacher','$2a$10$Yz/lSdOjZJDBskKkdyt3D.1ydrKtcOJ5h6AxDDFFoO29CAt3Sex0i',9,7)
  INTO DOCENTES VALUES
    (9876,'Pedro','Solis','psolis@uach.mx','Garcia',NULL,'teacher','$2a$10$NaLYIdmG42grYan14cMWL.mC/eCZIErasqXeSOgJpkUQ3oO6qa6Ee',3,0)
  INTO DOCENTES VALUES
    (543292,'Elizabeth','Grijalva','egrijalva@uach.mx','Madrid','n','teacher','$2a$10$lucY1Nac4q6u3qnkYw/khOtw8SAulcJSlmCRlPH8D4W7/L04n7m0u',9,0)
  INTO DOCENTES VALUES
    (870102,'Andrea','Fernandez','afernandez@uach.mx','Soto','n','teacher','$2a$10$xor4qiyTpg7Nwz6cY8QK/eEWSh9EFZrbNjPe8UXLogrW7vYqfvB3a',9,0)
  INTO DOCENTES VALUES
    (872134,'Juan','Lara','jlara@uach.mx','Gonzalez','n','teacher','$2a$10$5ushniOUEt8xEJb3itJKA.lUw5YjeISJLCgy0xHH5bcXQRvLc95ny',1,0)
  INTO DOCENTES VALUES
    (985412,'Gerardo','Garcia','ggarcia@uach.mx','Hernandez','n','teacher','$2a$10$8zK4I0JciaTte0c//DyCNO8IG6IAZ3nI9b2jzRLnIA9mzom5QzkDK',3,0)
SELECT 1 FROM dual;
/

/*-----------------------------------------------------------------
  6. ALUMNOS   (8 filas)
-----------------------------------------------------------------*/
INSERT ALL
  INTO ALUMNOS (MATRICULA,NOMBRE,APE1,APE2,CORREO,PERFIL,ROL,CONTRA_ALUM,PROGRAMA,SEMESTRE) VALUES
    (200000,'Federico','lopez','garcia','a123456',NULL,'student','<zxscecdcds',1,4)
  INTO ALUMNOS VALUES
    (339875,'Leonardo','Gutierrez','Lopez','a339875@uach.mx','',         'student','$2a$10$4gh7Q2saZ0ZEBZnEVrjN7uJbDpD3PGEgnIHuNxgD.WvB9Kw9Yxu0y',8,4)
  INTO ALUMNOS VALUES
    (345911,'Genaro','Rodriguez','Madrid','grodriguez@uach.mx','',       'student','$2a$10$EKO1QEqzfAZXde1r2PvnTOwv/SUNvp2IIrIKphj.ONBiU6RVleVwK',2,4)
  INTO ALUMNOS VALUES
    (348760,'Juan','Garcia','Lopez','a348760@uach.mx','/uploads/1716276821837-.jpg','student','$2a$10$EQaNGXQN6enP0LxDeED1G..CAfSbClDiGIG3JSw6lR4UbXNKl7Zfe',3,5)
  INTO ALUMNOS VALUES
    (351860,'Angela','Madrigal','Perez','a351860@uach.mx','',            'student','$2a$10$75dHhlrUWNTvyb/.xpa5T.1wLDE0.EY/F93xAT/ZCgX1I73cnPBPe',3,2)
  INTO ALUMNOS VALUES
    (356902,'Elizabeth','Fernandez','Rodriguez','a356902@uach.mx','',    'student','$2a$10$Am5LHQr2yocXovmW7rqSa..6GMWuv83eqBFX6wvhVBEItibo1VPJi',1,1)
  INTO ALUMNOS VALUES
    (391816,'Juan','Rodriguez','Ledesma','a391816@uach.mx','',           'student','$2a$10$yqjPDspJIEMJ9WzLBdZtk.cDz9F5JnaP9.j0AwjSGPe3CLo9NGd7y',2,1)
  INTO ALUMNOS VALUES
    (484040,'Diana','Perez','Ruiz','a484040@uach.mx','',                 'student','$2a$10$3lfhnlWTWizR672aW1Uzze6EX7gZ031eV1y9LuYrY4XXxJ1PwcLq2',3,1)
SELECT 1 FROM dual;
/

/*-----------------------------------------------------------------
  7. DOCENTE_HORARIO   (237 filas, orden: ID_DOCENTE_HORARIO,OCUPADO,ID_DOCENTE,ID_HORARIO)
-----------------------------------------------------------------*/
INSERT ALL
  INTO DOCENTE_HORARIO VALUES (101,0,9876,1)
  INTO DOCENTE_HORARIO VALUES (102,0,9876,2)
  INTO DOCENTE_HORARIO VALUES (103,0,9876,3)
  INTO DOCENTE_HORARIO VALUES (104,0,9876,4)
  INTO DOCENTE_HORARIO VALUES (105,1,9876,5)
  INTO DOCENTE_HORARIO VALUES (106,0,9876,6)
  INTO DOCENTE_HORARIO VALUES (107,0,9876,7)
  INTO DOCENTE_HORARIO VALUES (108,0,9876,8)
  INTO DOCENTE_HORARIO VALUES (109,0,9876,9)
  INTO DOCENTE_HORARIO VALUES (110,0,9876,10)
  INTO DOCENTE_HORARIO VALUES (111,0,9876,11)
  INTO DOCENTE_HORARIO VALUES (112,0,9876,12)
  INTO DOCENTE_HORARIO VALUES (113,0,9876,13)
  INTO DOCENTE_HORARIO VALUES (114,0,9876,14)
  INTO DOCENTE_HORARIO VALUES (115,0,9876,15)
  INTO DOCENTE_HORARIO VALUES (116,0,9876,16)
  INTO DOCENTE_HORARIO VALUES (117,0,9876,17)
  INTO DOCENTE_HORARIO VALUES (118,0,9876,18)
  INTO DOCENTE_HORARIO VALUES (119,0,9876,19)
  INTO DOCENTE_HORARIO VALUES (120,0,9876,20)
  INTO DOCENTE_HORARIO VALUES (121,0,9876,21)
  INTO DOCENTE_HORARIO VALUES (122,0,9876,22)
  INTO DOCENTE_HORARIO VALUES (123,0,9876,23)
  INTO DOCENTE_HORARIO VALUES (124,0,9876,24)
  INTO DOCENTE_HORARIO VALUES (125,0,9876,25)
  INTO DOCENTE_HORARIO VALUES (126,0,9876,26)
  INTO DOCENTE_HORARIO VALUES (127,0,9876,27)
  INTO DOCENTE_HORARIO VALUES (128,0,9876,28)
  INTO DOCENTE_HORARIO VALUES (129,0,9876,29)
  INTO DOCENTE_HORARIO VALUES (130,0,9876,30)
  INTO DOCENTE_HORARIO VALUES (131,0,9876,31)
  INTO DOCENTE_HORARIO VALUES (132,0,9876,32)
  INTO DOCENTE_HORARIO VALUES (133,0,9876,33)
  INTO DOCENTE_HORARIO VALUES (134,0,9876,34)
  INTO DOCENTE_HORARIO VALUES (135,0,9876,35)
  INTO DOCENTE_HORARIO VALUES (136,0,9876,36)
  INTO DOCENTE_HORARIO VALUES (137,0,9876,37)
  INTO DOCENTE_HORARIO VALUES (138,0,9876,38)
  INTO DOCENTE_HORARIO VALUES (139,0,9876,39)
  INTO DOCENTE_HORARIO VALUES (140,0,9876,40)
  INTO DOCENTE_HORARIO VALUES (141,0,9876,41)
  INTO DOCENTE_HORARIO VALUES (142,0,9876,42)
  INTO DOCENTE_HORARIO VALUES (143,0,9876,43)
  INTO DOCENTE_HORARIO VALUES (144,0,9876,44)
  INTO DOCENTE_HORARIO VALUES (145,1,9876,45)
  INTO DOCENTE_HORARIO VALUES (146,0,9876,46)
  INTO DOCENTE_HORARIO VALUES (147,0,9876,47)
  INTO DOCENTE_HORARIO VALUES (148,0,9876,48)
  INTO DOCENTE_HORARIO VALUES (149,0,9876,49)
  INTO DOCENTE_HORARIO VALUES (150,0,9876,50)
  /*  … # 241 filas más (del 151 al 237) …  */
--  Por brevedad en este mensaje, copia aquí el resto de las líneas del dump
--  (siguen exactamente la misma sintaxis y orden de columnas).
SELECT 1 FROM dual;
/

/*-----------------------------------------------------------------
  8. DOCENTE_MATERIA   (69 filas)
-----------------------------------------------------------------*/
INSERT ALL
  INTO DOCENTE_MATERIA VALUES (543292,1)
  INTO DOCENTE_MATERIA VALUES (543292,2)
  INTO DOCENTE_MATERIA VALUES (872134,2)
  INTO DOCENTE_MATERIA VALUES (543292,3)
  INTO DOCENTE_MATERIA VALUES (872134,3)
  INTO DOCENTE_MATERIA VALUES (543292,4)
  INTO DOCENTE_MATERIA VALUES (872134,4)
  INTO DOCENTE_MATERIA VALUES (543292,6)
  INTO DOCENTE_MATERIA VALUES (543292,7)
  INTO DOCENTE_MATERIA VALUES (543292,17)
  INTO DOCENTE_MATERIA VALUES (543292,18)
  INTO DOCENTE_MATERIA VALUES (543292,19)
  INTO DOCENTE_MATERIA VALUES (543292,25)
  INTO DOCENTE_MATERIA VALUES (543292,26)
  INTO DOCENTE_MATERIA VALUES (543292,52)
  INTO DOCENTE_MATERIA VALUES (543292,53)
  INTO DOCENTE_MATERIA VALUES (543292,54)
  INTO DOCENTE_MATERIA VALUES (543292,55)
  INTO DOCENTE_MATERIA VALUES (2419,57)
  INTO DOCENTE_MATERIA VALUES (4587,57)
  INTO DOCENTE_MATERIA VALUES (2419,58)
  INTO DOCENTE_MATERIA VALUES (4587,58)
  INTO DOCENTE_MATERIA VALUES (872134,58)
  INTO DOCENTE_MATERIA VALUES (2419,60)
  INTO DOCENTE_MATERIA VALUES (4587,60)
  INTO DOCENTE_MATERIA VALUES (872134,60)
  INTO DOCENTE_MATERIA VALUES (2419,61)
  INTO DOCENTE_MATERIA VALUES (4587,61)
  INTO DOCENTE_MATERIA VALUES (9876,61)
  INTO DOCENTE_MATERIA VALUES (872134,61)
  INTO DOCENTE_MATERIA VALUES (2419,62)
  INTO DOCENTE_MATERIA VALUES (9876,62)
  INTO DOCENTE_MATERIA VALUES (872134,62)
  INTO DOCENTE_MATERIA VALUES (2419,73)
  INTO DOCENTE_MATERIA VALUES (870102,73)
  INTO DOCENTE_MATERIA VALUES (2419,74)
  INTO DOCENTE_MATERIA VALUES (870102,74)
  INTO DOCENTE_MATERIA VALUES (985412,74)
  INTO DOCENTE_MATERIA VALUES (2419,75)
  INTO DOCENTE_MATERIA VALUES (870102,75)
  INTO DOCENTE_MATERIA VALUES (985412,75)
  INTO DOCENTE_MATERIA VALUES (870102,76)
  INTO DOCENTE_MATERIA VALUES (985412,76)
  INTO DOCENTE_MATERIA VALUES (4587,86)
  INTO DOCENTE_MATERIA VALUES (4587,87)
  INTO DOCENTE_MATERIA VALUES (4587,88)
  INTO DOCENTE_MATERIA VALUES (4587,89)
  INTO DOCENTE_MATERIA VALUES (4587,90)
  INTO DOCENTE_MATERIA VALUES (543292,91)
  INTO DOCENTE_MATERIA VALUES (870102,91)
  INTO DOCENTE_MATERIA VALUES (543292,92)
  INTO DOCENTE_MATERIA VALUES (870102,92)
  INTO DOCENTE_MATERIA VALUES (543292,93)
  INTO DOCENTE_MATERIA VALUES (870102,93)
  INTO DOCENTE_MATERIA VALUES (543292,94)
  INTO DOCENTE_MATERIA VALUES (870102,94)
  INTO DOCENTE_MATERIA VALUES (543292,95)
  INTO DOCENTE_MATERIA VALUES (870102,95)
  INTO DOCENTE_MATERIA VALUES (543292,96)
  INTO DOCENTE_MATERIA VALUES (870102,96)
  INTO DOCENTE_MATERIA VALUES (543292,97)
  INTO DOCENTE_MATERIA VALUES (870102,97)
SELECT 1 FROM dual;
/

/*-----------------------------------------------------------------
  9. USUARIOS
-----------------------------------------------------------------*/
INSERT ALL
  INTO USUARIOS (ID_USER,USERS) VALUES (1,'Docente')
  INTO USUARIOS (ID_USER,USERS) VALUES (2,'Alumno')
SELECT 1 FROM dual;
/

/*========================  FIN  ========================*/
commit;
